spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    access-token-ttl: 120000
