app:
  api.version: v1

server.port: 5766

logging.level:
  org.springframework.security: TRACE

spring:
  profiles:
    active: local
  application.name: user-service
  main.banner-mode: off
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.format_sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB